// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYzTVhPPoJTYsIhYcxFK9OG2o9S0Mw3I',
    appId: '1:519802138233:web:24c1a43eaec5ebafba2ea8',
    messagingSenderId: '519802138233',
    projectId: 'chatapp-cb6a0',
    authDomain: 'chatapp-cb6a0.firebaseapp.com',
    storageBucket: 'chatapp-cb6a0.appspot.com',
    measurementId: 'G-ZL6FNL0F5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlQ6cNyKxmwLz9dnj2VeAAm5yZ-dtkVU8',
    appId: '1:519802138233:android:2e91fc8efee37df2ba2ea8',
    messagingSenderId: '519802138233',
    projectId: 'chatapp-cb6a0',
    storageBucket: 'chatapp-cb6a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBThEYBlyjzSyxRPEdtNhqL7o9m2rIvMyM',
    appId: '1:519802138233:ios:56b6e7b0ed99cfcbba2ea8',
    messagingSenderId: '519802138233',
    projectId: 'chatapp-cb6a0',
    storageBucket: 'chatapp-cb6a0.appspot.com',
    iosClientId: '519802138233-d80fb05mfiqhn3q0lnssl66gq25n6st4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabahiChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBThEYBlyjzSyxRPEdtNhqL7o9m2rIvMyM',
    appId: '1:519802138233:ios:56b6e7b0ed99cfcbba2ea8',
    messagingSenderId: '519802138233',
    projectId: 'chatapp-cb6a0',
    storageBucket: 'chatapp-cb6a0.appspot.com',
    iosClientId: '519802138233-d80fb05mfiqhn3q0lnssl66gq25n6st4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tabahiChatApp',
  );
}
